
# ---------------------- Language Array ------------------
multilingual_content = {
    'english': {
        # ---------- Title -------------
        'title_home' : 'Fellowship | Home',
        # ----- Top Menu -----
        'skip-to-main-content': 'Skip to Main Content',
        'mobile-no': '020-26333330, 26333339, 26343600',
        'a-': 'A-',
        'a': 'A',
        'a+': 'A+',
        'english': 'English',
        'marathi': 'Marathi',
        'trti_header':'Dr. Babasaheb Ambedkar Research and Training Institute (BARTI)',
        'admin_login_btn':'Admin Login',
        'fellowship': 'Fellowship',

        # -----------------------Leaders ----------------------
        'eknath_shinde': 'Shri. Eknath Shinde',
        'eknath_shinde_desgn': "Hon'ble Deputy Chief Minister, Maharashtra State",
        'dev_phad':'Shri. Devendra Fadnavis',
        'dev_phad_desgn':"Hon'ble Chief Minister, Maharashtra State",
        'ajit_pawar':'Shri. Ajit Pawar',
        'ajit_pawar_desgn':"Hon'ble Deputy Chief Minister, Maharashtra State",
        'vijay_gavit':'Dr. Vijaykumar Gavit',
        'vijay_gavit_desgn':"Hon'ble Minister, Tribal Development Department",
        'vijay_waghmare':"Dr. Harshdeep Kamble, I.A.S.",
        'vijay_waghmare_desgn':"Honb'le Principal secretary, Social Justice and Special Assistance Department",
        'sanjay_shirsat':"Mr. Sanjay Shirsat ",
        'sanjay_shirsat_design':"Hon'ble Minister of Social Justice, Government of Maharashtra",
        'madhuri_misal': "Mrs. Madhuri Misal",
        'madhuri_misal_design':"Hon'ble State Minister of Social Justice, Government of Maharashtra",
        'sunil_ware': "Mr. Sunil Ware, IRAS",
        'sunil_ware_design':"Director General, Dr. Babasaheb Ambedkar Research and Training Institute (BARTI), Pune",

        # --------------- Menubar -----------------
        'home' : 'Home',
        'about': "About",
        'government_regulation' : 'Circulars/Orders',
        'government_decision':'Government Decision',
        'circulars':'Circulars',
        'shcolarship_regulations':'Scholarship Regulations',
        'margadarshak':'Guidance Information',
        'video':'Videos - FAQ',
        'contact_us' : 'Contact Us',
        'charts': 'Reports',
        'login_sign_btn':'Login | Sign up',

        # ------------------ Banner Section ---------------------
        'total_applications' : "Total Application",
        'total_applications_2022' : "Total Application 2022",
        'total_applications_2021' : "Total Application 2021",
        'fellowship_awarded' : 'Fellowship Awarded',
        'fellowship_completed' : 'Fellowship Completed',
        'this_yrs_application' : 'This Year Applications',
        'get_your_fellowship_now' : 'Get Your Fellowship Now',
        'enroll_here' : 'Enroll Here',

        #------------------------ About --------------------------
        'about_the_institute' : 'About The Institution',
        'about_title' : 'Dr. Babasaheb Ambedkar Research and Training Institute (BARTI), Pune',
        'read_more' : "Read More",
        'criteria' : "Criteria",
        'scheme_benefits' : 'Scheme Benefits',
        'eligibility_criteria' : 'Eligibility Criteria',
        'updates' : 'Updates',
        'how_to_enroll' : 'How to enroll?',
        'step' : 'Step',
        'step_1_content' : 'Create Your Login or Sign on site',
        'step_2_content' : 'Fill Application Form',
        'step_3_content' : 'Get Selected by Admin',
        'step_4_content' : 'Upload Joining Letter of PhD',
        'step_5_content' : 'Get your Fellowship',

        'faq' : 'Frequently Asked Questions',
        'q1' : 'How many Fellows do you select?',
        'ans1': 'We hire 100 students every year',
        'q2' : 'I wasn’t selected, can I receive feedback on my application?',
        'ans2' : 'We will send you feedback through email, and it will be reflected on your dashboard as well.',
        'related_links' : 'Related Links',
        'security_brands' : 'SECURITY & BRANDS',
        'address': "28, Queen's Garden Rd, Near Old Circuit House, Camp, Pune, Maharashtra 411001" ,
        'phone' : 'Phone',
        'email' : 'Email',
        'national_portal_of_india' : 'National Portal of India',
        'tribal_development_department' : 'Tribal development Department',
        'tribal_commissionerate' : 'Tribal Commissionerate',
        'aaple_sarkar' : 'Aaple Sarkar',
        'ministry_of_tribal_affairs' : 'Ministry of Tribal Affairs- Govt of India',
        'my_gov' : 'My Gov',
        'security_brand' : 'SECURITY & BRAND',
        'hyperlink_policy' : 'Hyperlink Policy',
        'terms_and_conditions' : 'Terms and Conditions',
        'privacy_policy' : 'Privacy Policy',
        'copyright_policy' : 'Copyright Policy',
        'website_monitoring_policy' : 'Website Monitoring Policy',
        'sitemap' : 'Sitemap',
        'footer_text' : 'Website Content Owned & Managed by Dr. Babasaheb Ambedkar Research and Training Institute | Maharashtra, India',
        'desgn_dev' : 'Designed and Developed by',
        'ics' : 'Integrated Consultancy Services ',
        'you_name' : 'Your Name',
        'you_email' : 'Your Email',
        'subject' : 'Subject',
        'message' : 'Message',
        'send_message' : 'Send Message',
        'address' : 'Address',
        'address_text' : "28, QUEEN'S GARDEN RD, NEAR OLD CIRCUIT HOUSE, CAMP, PUNE, MAHARASHTRA 411001",
        'email_us' : 'Email us',
        'open_hours': 'Open hours',
        'monday_friday' : 'Monday - Friday',
        'year_wise_total':'Year Wise Total Application',
        'gender_ratio': 'Gender Ratio',
        'disability_count': 'Disability Count'

    },
    'marathi': {
        # ----------- Title -------------
        'title_home' : 'अधिछात्रवृत्ती | मुख्यपृष्ठ',

        # ----- Top Menu -----
        'skip-to-main-content': 'मुख्य सामग्रीवर जा',
        'mobile-no': '०२०-२६३३३३३०, २६३३३३३९, २६३४३६००',
        'a-': 'ए-',
        'a': 'ए',
        'a+': 'ए+',
        'english': 'इंग्रजी',
        'marathi': 'मराठी',
        'trti_header':'डॉ. बाबासाहेब आंबेडकर संशोधन व प्रशिक्षण संस्था (बार्टी)',
        'admin_login_btn':'प्रशासक लॉगिन',
        'fellowship': 'अधिछात्रवृत्ती',

        # -----------------------Leaders ----------------------
        'eknath_shinde': 'श्री. एकनाथ शिंदे',
        'eknath_shinde_desgn': "माननीय उपमुख्यमंत्री, महाराष्ट्र राज्य",
        'dev_phad':'श्री. देवेंद्र फडणवीस',
        'dev_phad_desgn':"माननीय मुख्यमंत्री, महाराष्ट्र राज्य",
        'ajit_pawar':'श्री. अजित पवार',
        'ajit_pawar_desgn':'माननीय उपमुख्यमंत्री, महाराष्ट्र राज्य',
        'vijay_gavit':'डॉ. विजयकुमार गावित',
        'vijay_gavit_desgn':"माननीय मंत्री, आदिवासी विकास विभाग",
        'vijay_waghmare':"डॉ. हर्षदीप कांबळे, IAS",
        'vijay_waghmare_desgn':"मा. प्रधान सचिव, सामाजिक न्याय आणि विशेष सहाय्य विभाग",
        'sanjay_shirsat':"श्री. संजय शिरसाट",
        'sanjay_shirsat_design':"मा. सामाजिक न्याय मंत्री, महाराष्ट्र राज्य",
        'madhuri_misal': "श्रीमती. माधुरी मिसाळ",
        'madhuri_misal_design':"मा. राज्य सामाजिक न्याय मंत्री, महाराष्ट्र राज्य",
        'sunil_ware': "श्री. सुनील वारे, IRAS ",
        'sunil_ware_design':"महासंचालक, डॉ. बाबासाहेब आंबेडकर संशोधन व प्रशिक्षण संस्था (बार्टी), पुणे",

        # --------------- Menubar -----------------
        'home' : 'मुख्यपृष्ठ',
        'about': "आमच्याविषयी",
        'government_regulation' : 'परिपत्रके/आदेश',

        'contact_us' : 'संपर्क',
        'charts' : 'अहवाल',
        'login_sign_btn':'लॉगिन | साइन अप करा',
        'government_decision':'सरकारी  निर्णय',
        'margadarshak':'मार्गदर्शक सूचना',
        'circulars':'परिपत्रके',
        'shcolarship_regulations':'अधिछात्रवृत्ती नियमावली',
        # ------------------ Banner Section ---------------------
        'total_applications' : "एकूण अर्ज",
        'total_applications_2022' : "एकूण अर्ज 2022",
        'total_applications_2021' : "एकूण अर्ज 2021",
        'fellowship_awarded' : 'अधिछात्रवृत्ती प्रदान',
        'fellowship_completed' : 'अधिछात्रवृत्ती पूर्ण केलेले',
        'this_yrs_application' : 'या वर्षाचे अर्ज',
        'enroll_here' : 'येथे नावनोंदणी करा',
        'get_your_fellowship_now' : 'आता आपली अधिछात्रवृत्ती मिळवा',


        # ----------------------------- About institute ---------------------
        'about_the_institute' : 'संस्थेबद्दल',
        'about_title' : 'डॉ. बाबासाहेब आंबेडकर संशोधन व प्रशिक्षण संस्था (बार्टी), पुणे',
        'read_more' : "पुढे वाचा",

        # ---------------------------
        'criteria' : "निकष",
        'scheme_benefits' : 'योजनेचे फायदे',
        'eligibility_criteria' : 'पात्रता निकष',
        'updates' : 'अपडेट्स',
        'how_to_enroll' : 'नोंदणी कशी करावी?',
        'step' : 'स्टेप',
        'step_1_content' : 'साइटवर आपले लॉगिन तयार करा किंवा साइन इन करा',
        'step_2_content' : 'अर्ज भरा',
        'step_3_content' : 'प्रशासकाद्वारे निवड मिळवा',
        'step_4_content' : 'पीएचडीचे सामील पत्र अपलोड करा',
        'step_5_content' : 'तुमची फेलोशिप मिळवा',

        'faq' : 'वारंवार विचारले जाणारे प्रश्न',
        'video' : 'व्हिडिओ - वारंवार विचारले जाणारे प्रश्न',
        'q1' : 'तुम्ही किती विद्यार्थी निवडता?',
        'ans1': 'आम्ही दरवर्षी 100 विद्यार्थी निवडतो',
        'q2' : 'मी निवडलो नाही, मला अभिप्राय मिळू शकेल का माझ्या अर्जावर?',
        'ans2' : 'आम्ही आपल्याला ईमेलद्वारे अभिप्राय पाठवू आणि ते आपल्या डॅशबोर्डवर देखील प्रतिबिंबित होईल.',
        'related_links' : 'संबंधित दुवे',
        'security_brands' : 'सुरक्षा आणि ब्रँड',

        'address': '२८, क्वीन्स गार्डन रोड, जवळ जुन्या सर्किट हाऊस, कॅम्प, पुणे, महाराष्ट्र ४११००१',
        'phone' : 'फोन',
        'email' : 'ईमेल',
        'national_portal_of_india' : 'भारताचा राष्ट्रीय पोर्टल',
        'tribal_development_department' : 'आदिवासी विकास विभाग',
        'tribal_commissionerate' : 'आदिवासी आयुक्त',
        'aaple_sarkar' : 'आपले सरकार',
        'ministry_of_tribal_affairs' : 'आदिवासी प्रकरण मंत्रालय- भारत सरकार',
        'my_gov' : 'माय गोव्ह',
        'security_brand' : 'सुरक्षा आणि ब्रँड',
        'hyperlink_policy' : 'हायपरलिंक धोरण',
        'terms_and_conditions' : 'नियम आणि अटी',
        'privacy_policy' : 'गोपनीयता धोरण',
        'copyright_policy' : 'कॉपीराइट धोरण',
        'website_monitoring_policy' : 'वेबसाइट देखरेख धोरण',
        'sitemap' : 'साइटमॅप',
        'footer_text' : 'वेबसाइट सामग्री डॉ. बाबासाहेब आंबेडकर संशोधन व प्रशिक्षण संस्था (बार्टी) संस्थेच्या मालकीची आणि व्यवस्थापित | महाराष्ट्र शासन, भारत',
        'desgn_dev' : ' डिझाइन आणि विकसित बाय',
        'ics' : 'इंटिग्रेटएड कन्सल्टन्सी सरवीसेस',
        'you_name' : 'तुमचे नाव',
        'you_email' : 'आपला ई - मेल',
        'subject' : 'विषय',
        'message' : 'संदेश',
        'send_message' : 'संदेश पाठवा',
        'address' : 'पत्ता',
        'call_us' : 'आम्हाला कॉल करा',
        'trti': 'आदिवासी संशोधन आणि प्रशिक्षण संस्था',
        'address_text' : '28, क्वीन्स गार्डन आरडी, ओल्ड  सर्किट हाऊसजवळ, कॅम्प, पुणे, महाराष्ट्र 411001',
        'email_us' : 'आम्हाला ईमेल करा',
        'open_hours': 'उघडे तास',
        'monday_friday' : 'सोमवार-शुक्रवार',
        'year_wise_total':'वर्षनिहाय एकूण अर्ज',
        'gender_ratio': 'लिंग गुणोत्तर',
        'disability_count': 'अपंगत्व संख्या'
    },
    # Add more languages and content as needed.
}